# Back Propagation 예제

### 예제와 동일한 형태의 neural network 구현하기


- 2-layer Neural Network without bias


In [1]:
import tensorflow as tf

# input data X와 정답 Y
X = tf.Variable([[2], [3]], dtype=tf.float32)
Y = tf.Variable([1], dtype=tf.float32)

# 첫번째 layer W_1, 두번째 layer W_2
W_1 = tf.Variable([[0.11, 0.21], [0.12, 0.08]])
W_2 = tf.Variable([[0.14, 0.15]])

In [2]:
# forward 연산
with tf.GradientTape() as tape:
  H_1 = tf.matmul(W_1, X)
  Y_hat = tf.matmul(W_2, H_1)
  Loss = tf.square(Y_hat - Y) * 1/2
  
print("hidden nodes : ", H_1)
print("Y_hat : ", Y_hat)
print("Loss : ", Loss)

hidden nodes :  tf.Tensor(
[[0.84999996]
 [0.48      ]], shape=(2, 1), dtype=float32)
Y_hat :  tf.Tensor([[0.191]], shape=(1, 1), dtype=float32)
Loss :  tf.Tensor([[0.32724053]], shape=(1, 1), dtype=float32)


In [3]:
# backward 연산 (모델 파라미터에 대해 gradient 계산)
(dLoss_dW_1, dLoss_dW_2) = tape.gradient(Loss, [W_1, W_2])
print(dLoss_dW_1)
print(dLoss_dW_2)

tf.Tensor(
[[-0.22652    -0.33978   ]
 [-0.24270001 -0.36405003]], shape=(2, 2), dtype=float32)
tf.Tensor([[-0.68764997 -0.38832   ]], shape=(1, 2), dtype=float32)


In [4]:
# learning rate 설정
lr = 0.05

# 모델 파라미터 업데이트
W_1 = W_1 - lr * dLoss_dW_1
W_2 = W_2 - lr * dLoss_dW_2

# 업데이트 된 모델로 다시 forward 연산
H_1 = tf.matmul(W_1, X)
Y_hat = tf.matmul(W_2, H_1)
Loss = tf.square(Y_hat - Y) * 1/2

# Y_hat 값이 Y 값에 가까워지고, Loss 값이 작아진 것을 확인할 수 있음  
print("hidden nodes : ", H_1)
print("Y_hat : ", Y_hat)
print("Loss : ", Loss)



hidden nodes :  tf.Tensor(
[[0.92361903]
 [0.55887747]], shape=(2, 1), dtype=float32)
Y_hat :  tf.Tensor([[0.2557458]], shape=(1, 1), dtype=float32)
Loss :  tf.Tensor([[0.27695718]], shape=(1, 1), dtype=float32)
